### ISSUE TITLE
Alignment of elements

### ISSUE THREAD

**Issue by Luapsi** [SKB-CGN/ioBroker.energiefluss-erweitert#94] opened 2023-11-01 18:54 UTC
**Describe the bug**  
The function for aligning a data field "Left" or "Right" are swapped!

**Expected behavior**  

 
![2023-11-01_194416_right instead of left](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/149511288/63e4c1ad-19ac-410b-8d97-821a21934d3f)
![2023-11-01_194436_left instead of right](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/149511288/8ff72229-27ef-4a32-a580-11b1f53d2f9d)
![2023-11-01_194352_center](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/149511288/a57b58d1-b3a1-417a-9133-f2541d242cbf)

 - Adapter version: v0.0.2-alpha.23
 - JS-Controller version:  v18.18.2
 - Node version: 9.8.1
 - Operating system: Windows10

Greetings Luapsi

**Comment by SKB-CGN** [comment] 2023-11-01 19:44
They are not swapped.

Place more items under each other and check, how the alignment is.

**Comment by SKB-CGN** [comment] 2023-11-04 08:32
If the issue is solved, please remember to close the issue.

Thank you in advance!

**Closed** 2023-11-07 08:35 UTC
Labels: question
